[build]
target = "x86_64-blog_os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[target."x86_64-blog_os.json"]
runner = "bootimage runner"
